// <auto-generated />
using System;
using FakeGundamWikiAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FakeGundamWikiAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240506000317_ChangeExampleResult")]
    partial class ChangeExampleResult
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.Affiliation", b =>
                {
                    b.Property<int>("AffiliationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AffiliationId"));

                    b.Property<string>("AffiliationName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AffiliationPurpose")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(30)");

                    b.HasKey("AffiliationId");

                    b.HasIndex("AffiliationName")
                        .IsUnique();

                    b.ToTable("Affiliations");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<string>("CharacterAliases")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CharacterBirthDate")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CharacterClassification")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("CharacterGenderId")
                        .HasColumnType("int");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(30)");

                    b.HasKey("CharacterId");

                    b.HasIndex("CharacterName")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.CharacterAffiliation", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("AffiliationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(30)");

                    b.HasKey("CharacterId", "AffiliationId");

                    b.HasIndex("AffiliationId");

                    b.ToTable("CharacterAffiliations");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.Example", b =>
                {
                    b.Property<int>("ExampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExampleId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ExampleCode")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ExampleName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ExampleResult")
                        .HasColumnType("varchar(5000)");

                    b.Property<int>("ExampleTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(30)");

                    b.HasKey("ExampleId");

                    b.HasIndex("ExampleTypeId");

                    b.ToTable("Examples");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.ExampleType", b =>
                {
                    b.Property<int>("ExampleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExampleTypeId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ExampleTypeName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(30)");

                    b.HasKey("ExampleTypeId");

                    b.HasIndex("ExampleTypeName")
                        .IsUnique();

                    b.ToTable("ExampleTypes");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufacturerId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("ManufacturerId");

                    b.HasIndex("ManufacturerName")
                        .IsUnique();

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.MobileSuit", b =>
                {
                    b.Property<int>("MobileSuitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MobileSuitId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("MobileSuitFirstSeen")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MobileSuitLastSeen")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MobileSuitName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MobileSuitUnitType")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SerieId")
                        .HasColumnType("int");

                    b.HasKey("MobileSuitId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("MobileSuitName")
                        .IsUnique();

                    b.HasIndex("SerieId");

                    b.ToTable("MobileSuits");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.MobileSuitPilot", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("MobileSuitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(30)");

                    b.HasKey("CharacterId", "MobileSuitId");

                    b.HasIndex("MobileSuitId");

                    b.ToTable("MobileSuitPilots");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("RefreshTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenValue")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.Serie", b =>
                {
                    b.Property<int>("SerieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SerieId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("SerieName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UniverseId")
                        .HasColumnType("int");

                    b.HasKey("SerieId");

                    b.HasIndex("SerieName")
                        .IsUnique();

                    b.HasIndex("UniverseId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.Universe", b =>
                {
                    b.Property<int>("UniverseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UniverseId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UniverseName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("UniverseId");

                    b.HasIndex("UniverseName")
                        .IsUnique();

                    b.ToTable("Universes");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("UserId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(30)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.CharacterAffiliation", b =>
                {
                    b.HasOne("FakeGundamWikiAPI.Data.Entities.Affiliation", "Affiliation")
                        .WithMany("CharacterAffiliations")
                        .HasForeignKey("AffiliationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FakeGundamWikiAPI.Data.Entities.Character", "Character")
                        .WithMany("CharacterAffiliations")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Affiliation");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.Example", b =>
                {
                    b.HasOne("FakeGundamWikiAPI.Data.Entities.ExampleType", "ExampleType")
                        .WithMany("Examples")
                        .HasForeignKey("ExampleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExampleType");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.MobileSuit", b =>
                {
                    b.HasOne("FakeGundamWikiAPI.Data.Entities.Manufacturer", "Manufacturer")
                        .WithMany("MobileSuits")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FakeGundamWikiAPI.Data.Entities.Serie", "Serie")
                        .WithMany()
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.MobileSuitPilot", b =>
                {
                    b.HasOne("FakeGundamWikiAPI.Data.Entities.Character", "Character")
                        .WithMany("MobileSuitPilots")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FakeGundamWikiAPI.Data.Entities.MobileSuit", "MobileSuit")
                        .WithMany("MobileSuitPilots")
                        .HasForeignKey("MobileSuitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("MobileSuit");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("FakeGundamWikiAPI.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.Serie", b =>
                {
                    b.HasOne("FakeGundamWikiAPI.Data.Entities.Universe", "Universe")
                        .WithMany("Series")
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.UserRole", b =>
                {
                    b.HasOne("FakeGundamWikiAPI.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FakeGundamWikiAPI.Data.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.Affiliation", b =>
                {
                    b.Navigation("CharacterAffiliations");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.Character", b =>
                {
                    b.Navigation("CharacterAffiliations");

                    b.Navigation("MobileSuitPilots");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.ExampleType", b =>
                {
                    b.Navigation("Examples");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.Manufacturer", b =>
                {
                    b.Navigation("MobileSuits");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.MobileSuit", b =>
                {
                    b.Navigation("MobileSuitPilots");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.Universe", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("FakeGundamWikiAPI.Data.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
