insert into Manufacturers
values ('Earth Federation', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Zimmad Company', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Neo Zeon', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Axis', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Anaheim Electronics', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('MIP Company', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Zeonic Company', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('N/A', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Earth Federation Forces', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('A Bao A Qu Mobile Suit Factory', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Principality of Zeon', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Titans', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Augusta Newtype Lab', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Zeonic', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Murasame Newtype Lab', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Konpeito Arsenal', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Oakland Newtype Lab', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('California Base Mobile Suit Factory', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Strategic Naval Research Institute', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('UNE/New UNE', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Neo Japan', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Vulture', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Neo Sweden', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Neo Hong Kong', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Delaz Fleet', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Jay Null', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('League Militaire', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Morgenroete', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Winner Corporation', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Morgenroete Inc.', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Unknown Human Civilization', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Sleeves', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Integrated Design Bureau', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Terminal', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Buch Concern', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Zeon Earth Attack Force', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('OZ', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Karaba', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Zodiac Alliance of Freedom Treaty', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Instructor H', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Devil Gundam', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
   ('Earth Alliance', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Augusta Newtype Laboratory', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Barton Foundation', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Professor G', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Master O', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Adukurf Mechano-Industries', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Shiro Kyoda', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Zimmad', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Casvals Neo Zeon', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Sthesia Awar', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('SNRI', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Jaburo', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Konpeitoh Arsenal', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('MO-V', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Jupiter Empire', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Howard', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Noisy Fairy Squadron', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Jupiter Republic', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('ReZeon', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Neo France', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('The Gundam Scientists', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Tolro Corporation', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Neo America', 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc');