insert into Series
values ('Mobile Suit Gundam', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam ZZ', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Zeta Gundam', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam 0083: Stardust Memory', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Gundam Sentinel', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Variation', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam 0080: War in the Pocket', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Advance of Zeta: The Flag of Titans', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam MS IGLOOA', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Harmony of Gundam', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam Side Story: The Blue Destiny', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam: The 08th MS Team', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam: Chars Counterattack', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Chars Counterattack Mobile Suit Variations', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam: Chars Counterattack - Beltorchikas Children', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam: Battlefield Record U.C. 0081', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam Unicorn', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('After War Gundam X', 4, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Fighter G Gundam', 2, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam: Extreme Vs.', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('UC-MSV', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam Wing', 3, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Victory Gundam', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam F91', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Crossbone Gundam', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam Unicorn - Bande Dessinee', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam SEED', 6, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('∀ Gundam', 5, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Variations', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam SEED Destiny', 6, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam Unicorn RE:0096', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam Twilight Axis', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam Narrative', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Moon Gundam', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam Hathaway', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam SEED Freedom', 6, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam: Gihrens Greed', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Zeta Gundam Mobile Suit Variations', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Plamo-Kyoshiro', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam MS IGLOO 603', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam MS IGLOO: Apocalypse 0079', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam (Novel)', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Gundam Breaker', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam Side Story: Missing Link', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam Extreme Vs. Maxi Boost ON', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Gundam the Ride: A Baoa Qu', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam MS IGLOO: The Hidden One Year War', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam Katana', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam Side Story 0079: Rise From The Ashes', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Gundam Stand at Jaburo', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam UC: One of Seventy Two', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Gundam Neo Experience 0087: Green Divers', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam 0083 Rebellion', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam UC: Neo Zeong Strikes Odaiba!', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Gundam Reconguista in G: From the Past to the Future', 8, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam 0083: Stardust Memory Picture Drama - The Mayfly of Space 2', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Gundam Legacy', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Crossbone Gundam: Skull Heart', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam Unicorn (Novel)', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam U.C. 0094: Across the Sky', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Crossbone Gundam: Ghost', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam: Cross Dimension 0079', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('MSV-R', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam UC Perfectibility', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Victory Gundam (Novel)', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam: Zeonic Front', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Gundam Unicorn Mobile Suit Variations', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('New Mobile Report Gundam Wing Dual Story: G-Unit', 3, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam Side Story: Space, To the End of a Flash', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Crossbone Gundam: Steel 7', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam Side Story: Missing Link (Manga)', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Advance of Zeta Re-Boot: Gundam Inle', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Anaheim Laboratory Log', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam F91 Prequel', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam Battle Operation Code Fairy', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam SEED ASTRAY Princess of the Sky', 6, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suits Gundam: Red Giant 03rd MS Team (Manga)', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam Aggressor', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Fukuchi Mobile Suit Station', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam U.C. ENGAGE', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc'),
  ('Mobile Suit Gundam F90: Fastest Formula', 1, 1, GETDATE(), 'dcaceresc', GETDATE(), 'dcaceresc');