global using Application.Common.Exceptions;
global using Application.Common.Interfaces;
global using Ardalis.GuardClauses;
global using AutoMapper;
global using AutoMapper.QueryableExtensions;
global using Domain.Entities;
global using FluentValidation;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
